# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KoalaAI_C2G.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11KoalaAI_C2G.proto\x12\x07msg.c2g\"\t\n\x07LinkReq\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"c\n\rGameConfigure\x12\r\n\x05mapId\x18\x01 \x01(\r\x12\x0f\n\x07numOfAI\x18\x02 \x01(\r\x12\x32\n\x10\x61gentInitOptions\x18\x03 \x03(\x0b\x32\x18.msg.c2g.AgentInitOption\"\xcd\x01\n\x0f\x41gentInitOption\x12\x0f\n\x07\x61gentId\x18\x01 \x01(\x04\x12\x11\n\tstartType\x18\x02 \x01(\r\x12\x18\n\x10targetPointLevel\x18\x03 \x01(\r\x12\x18\n\x10targetPointIndex\x18\x04 \x01(\r\x12(\n\rstartPosition\x18\x05 \x01(\x0b\x32\x11.msg.c2g.Vector3D\x12\x13\n\x0bsavePointId\x18\x06 \x01(\x04\x12#\n\x08velocity\x18\x07 \x01(\x0b\x32\x11.msg.c2g.Vector3D\"\x93\x01\n\x0f\x41IActionMessage\x12\x0f\n\x07\x61gentId\x18\x01 \x01(\x04\x12\"\n\x07moveDir\x18\x02 \x01(\x0b\x32\x11.msg.c2g.Vector2D\x12\x13\n\x0b\x61\x63tionsType\x18\x03 \x03(\r\x12\"\n\x07propDir\x18\x04 \x01(\x0b\x32\x11.msg.c2g.Vector2D\x12\x12\n\npauseState\x18\x05 \x01(\x08\"\xb0\x01\n\x0f\x41IServerMessage\x12-\n\x0bmessageType\x18\x01 \x01(\x0e\x32\x18.msg.c2g.AIServerMsgType\x12*\n\ngameConfig\x18\x02 \x01(\x0b\x32\x16.msg.c2g.GameConfigure\x12-\n\x0b\x61\x63tionOfAIs\x18\x03 \x03(\x0b\x32\x18.msg.c2g.AIActionMessage\x12\x13\n\x0bpauseAgents\x18\x04 \x01(\x08*9\n\x05\x43MD2G\x12\x12\n\x0e\x43MD2G_LINK_REQ\x10\x00\x12\x1c\n\x18\x43MD2G_A_I_SERVER_MESSAGE\x10\x01*^\n\x0f\x41IServerMsgType\x12\x18\n\x14GAME_GLOBAL_INFO_REQ\x10\x00\x12\x0e\n\nCHOOSE_MAP\x10\x01\x12\x11\n\rGAME_INIT_REQ\x10\x02\x12\x0e\n\nACTION_REQ\x10\x03\x42\x19\xaa\x02\x16Koala.Robot.AI.Msg.C2Gb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KoalaAI_C2G_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026Koala.Robot.AI.Msg.C2G'
  _globals['_CMD2G']._serialized_start=758
  _globals['_CMD2G']._serialized_end=815
  _globals['_AISERVERMSGTYPE']._serialized_start=817
  _globals['_AISERVERMSGTYPE']._serialized_end=911
  _globals['_LINKREQ']._serialized_start=30
  _globals['_LINKREQ']._serialized_end=39
  _globals['_VECTOR2D']._serialized_start=41
  _globals['_VECTOR2D']._serialized_end=73
  _globals['_VECTOR3D']._serialized_start=75
  _globals['_VECTOR3D']._serialized_end=118
  _globals['_GAMECONFIGURE']._serialized_start=120
  _globals['_GAMECONFIGURE']._serialized_end=219
  _globals['_AGENTINITOPTION']._serialized_start=222
  _globals['_AGENTINITOPTION']._serialized_end=427
  _globals['_AIACTIONMESSAGE']._serialized_start=430
  _globals['_AIACTIONMESSAGE']._serialized_end=577
  _globals['_AISERVERMESSAGE']._serialized_start=580
  _globals['_AISERVERMESSAGE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
